import { PrismaClient, type Prisma } from "@prisma/client";

import { normalizeDestinationName } from "../src/server/domain/destinations/normalize";
import { applyTurkishDestinationContent } from "./seed-turkish-content";

const prisma = new PrismaClient();

type SeedDestination = {
  slug: string;
  name: string;
  type: Prisma.DestinationCreateInput["type"];
  countryCode: string;
  countryName: string;
  regionName?: string;
  latitude?: number;
  longitude?: number;
  timezone?: string;
  primaryLanguage?: string;
  currencyCode?: string;
  shortDescription: string;
  longDescription: string;
  budgetLevel: Prisma.DestinationCreateInput["budgetLevel"];
  minimumRecommendedDays: number;
  maximumRecommendedDays: number;
  popularityScore: number;
  searchKeywords: string[];
  categories: string[];
  bestFor: string[];
  practicalNotes: string;
  isFeatured?: boolean;
  featuredPosition?: number;
};

/**
 * Internally curated development catalog.
 * Descriptions are original concise editorial text — not scraped provider copy.
 * No production photography URLs; hero images intentionally omitted.
 */
const SEED_DESTINATIONS: SeedDestination[] = [
  {
    slug: "istanbul",
    name: "Istanbul",
    type: "CITY",
    countryCode: "TR",
    countryName: "Türkiye",
    regionName: "Marmara",
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: "Europe/Istanbul",
    primaryLanguage: "tr",
    currencyCode: "TRY",
    shortDescription: "A crossroads of continents with historic quarters and vibrant food culture.",
    longDescription:
      "Istanbul blends Byzantine and Ottoman heritage with a lively modern city. Explore historic peninsulas, ferry rides on the Bosphorus, and neighborhoods that reward slow wandering.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 98,
    searchKeywords: ["istanbul", "constantinople", "bosphorus"],
    categories: ["HISTORY", "FOOD", "ART_AND_CULTURE", "ARCHITECTURE"],
    bestFor: ["FIRST_TIME_VISITORS", "COUPLES", "FOOD_TRIPS", "CULTURAL_TRIPS"],
    practicalNotes:
      "Public transit and ferries cover many areas. Card payments are common in tourist districts. Summers are warm; shoulder seasons are often more comfortable.",
    isFeatured: true,
    featuredPosition: 1,
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    type: "CITY",
    countryCode: "ES",
    countryName: "Spain",
    regionName: "Catalonia",
    latitude: 41.3874,
    longitude: 2.1686,
    timezone: "Europe/Madrid",
    primaryLanguage: "es",
    currencyCode: "EUR",
    shortDescription: "Mediterranean city life with Gaudí landmarks, beaches, and markets.",
    longDescription:
      "Barcelona pairs architectural landmarks with a walkable old town and a waterfront. Plan time for neighborhoods beyond the main tourist spine.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 95,
    searchKeywords: ["barcelona", "catalonia", "gaudi"],
    categories: ["ARCHITECTURE", "BEACH", "FOOD", "NIGHTLIFE"],
    bestFor: ["FIRST_TIME_VISITORS", "COUPLES", "FRIEND_GROUPS", "WEEKEND_TRIPS"],
    practicalNotes:
      "Metro and walking cover central districts. Late dining is common. Summer crowds are heavy around major landmarks.",
    isFeatured: true,
    featuredPosition: 2,
  },
  {
    slug: "lisbon",
    name: "Lisbon",
    type: "CITY",
    countryCode: "PT",
    countryName: "Portugal",
    regionName: "Lisbon",
    latitude: 38.7223,
    longitude: -9.1393,
    timezone: "Europe/Lisbon",
    primaryLanguage: "pt",
    currencyCode: "EUR",
    shortDescription: "Hilltop viewpoints, tiled streets, and Atlantic light.",
    longDescription:
      "Lisbon rewards travelers who enjoy tram rides, miradouro views, and day trips along the coast. The historic center is compact but hilly.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 92,
    searchKeywords: ["lisbon", "lisboa", "alfama"],
    categories: ["FOOD", "HISTORY", "PHOTOGRAPHY", "RELAXATION"],
    bestFor: ["COUPLES", "FIRST_TIME_VISITORS", "FOOD_TRIPS", "WEEKEND_TRIPS"],
    practicalNotes:
      "Trams and walking work well; expect steep streets. Card payments are widely accepted in the city center.",
    isFeatured: true,
    featuredPosition: 3,
  },
  {
    slug: "rome",
    name: "Rome",
    type: "CITY",
    countryCode: "IT",
    countryName: "Italy",
    regionName: "Lazio",
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
    currencyCode: "EUR",
    shortDescription: "Ancient landmarks and neighborhood trattorias across a sprawling capital.",
    longDescription:
      "Rome offers layered history from antiquity to the present. Build days around a few key sites and leave room for unplanned neighborhood walks.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 96,
    searchKeywords: ["rome", "roma", "colosseum"],
    categories: ["HISTORY", "FOOD", "ART_AND_CULTURE", "ARCHITECTURE"],
    bestFor: ["FIRST_TIME_VISITORS", "FAMILIES", "CULTURAL_TRIPS", "COUPLES"],
    practicalNotes:
      "Metro and walking cover tourist corridors. Book popular sites in advance when possible. Summers are hot and crowded.",
    isFeatured: true,
    featuredPosition: 4,
  },
  {
    slug: "florence",
    name: "Florence",
    type: "CITY",
    countryCode: "IT",
    countryName: "Italy",
    regionName: "Tuscany",
    latitude: 43.7696,
    longitude: 11.2558,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
    currencyCode: "EUR",
    shortDescription: "Renaissance art, compact historic streets, and Tuscan day trips.",
    longDescription:
      "Florence is ideal for museum lovers and walkers. The historic center is compact; surrounding Tuscan towns make strong day trips.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 88,
    searchKeywords: ["florence", "firenze", "tuscany"],
    categories: ["ART_AND_CULTURE", "HISTORY", "FOOD", "ARCHITECTURE"],
    bestFor: ["COUPLES", "CULTURAL_TRIPS", "FOOD_TRIPS"],
    practicalNotes:
      "Most sights are walkable. Museum tickets sell out in peak season. Consider trains for day trips.",
    isFeatured: false,
  },
  {
    slug: "paris",
    name: "Paris",
    type: "CITY",
    countryCode: "FR",
    countryName: "France",
    regionName: "Île-de-France",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    primaryLanguage: "fr",
    currencyCode: "EUR",
    shortDescription: "Museums, cafés, and riverfront neighborhoods in a classic capital.",
    longDescription:
      "Paris rewards both first-time visitors and return travelers who explore beyond a short checklist. Metro coverage makes neighborhood hopping easy.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 97,
    searchKeywords: ["paris", "france"],
    categories: ["ART_AND_CULTURE", "FOOD", "ARCHITECTURE", "SHOPPING"],
    bestFor: ["FIRST_TIME_VISITORS", "COUPLES", "CULTURAL_TRIPS", "FOOD_TRIPS"],
    practicalNotes:
      "Metro and walking are the usual ways to move. Many museums close one weekday. Peak summer and holiday periods are busy.",
    isFeatured: true,
    featuredPosition: 5,
  },
  {
    slug: "amsterdam",
    name: "Amsterdam",
    type: "CITY",
    countryCode: "NL",
    countryName: "Netherlands",
    regionName: "North Holland",
    latitude: 52.3676,
    longitude: 4.9041,
    timezone: "Europe/Amsterdam",
    primaryLanguage: "nl",
    currencyCode: "EUR",
    shortDescription: "Canals, museums, and bike-friendly neighborhoods.",
    longDescription:
      "Amsterdam is compact and easy to explore on foot or by bike. Museums and canal districts pair well with day trips into nearby towns.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 90,
    searchKeywords: ["amsterdam", "netherlands"],
    categories: ["ART_AND_CULTURE", "NIGHTLIFE", "ARCHITECTURE", "FAMILY"],
    bestFor: ["WEEKEND_TRIPS", "FRIEND_GROUPS", "COUPLES"],
    practicalNotes:
      "Trams and bikes are common. Watch for bike lanes. Popular museums often need advance tickets.",
  },
  {
    slug: "prague",
    name: "Prague",
    type: "CITY",
    countryCode: "CZ",
    countryName: "Czechia",
    regionName: "Prague",
    latitude: 50.0755,
    longitude: 14.4378,
    timezone: "Europe/Prague",
    primaryLanguage: "cs",
    currencyCode: "CZK",
    shortDescription: "Castle views, historic squares, and a walkable old town.",
    longDescription:
      "Prague’s historic core is dense with landmarks. Early mornings and evenings help avoid the busiest squares.",
    budgetLevel: "BUDGET",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 89,
    searchKeywords: ["prague", "praha"],
    categories: ["HISTORY", "ARCHITECTURE", "NIGHTLIFE", "FOOD"],
    bestFor: ["BUDGET_TRAVELERS", "WEEKEND_TRIPS", "FRIEND_GROUPS"],
    practicalNotes:
      "Trams and metro cover the city well. The historic center is best explored on foot. Peak summer can be crowded.",
  },
  {
    slug: "budapest",
    name: "Budapest",
    type: "CITY",
    countryCode: "HU",
    countryName: "Hungary",
    regionName: "Central Hungary",
    latitude: 47.4979,
    longitude: 19.0402,
    timezone: "Europe/Budapest",
    primaryLanguage: "hu",
    currencyCode: "HUF",
    shortDescription: "Thermal baths, riverside views, and ruin-bar nightlife.",
    longDescription:
      "Budapest spans both sides of the Danube with baths, viewpoints, and a lively food scene. Pair city walks with a bath visit.",
    budgetLevel: "BUDGET",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 87,
    searchKeywords: ["budapest", "hungary"],
    categories: ["HISTORY", "WELLNESS", "NIGHTLIFE", "FOOD"],
    bestFor: ["BUDGET_TRAVELERS", "COUPLES", "FRIEND_GROUPS"],
    practicalNotes:
      "Metro and trams are practical. Thermal baths are a highlight for many visitors. Card acceptance varies outside tourist areas.",
  },
  {
    slug: "vienna",
    name: "Vienna",
    type: "CITY",
    countryCode: "AT",
    countryName: "Austria",
    regionName: "Vienna",
    latitude: 48.2082,
    longitude: 16.3738,
    timezone: "Europe/Vienna",
    primaryLanguage: "de",
    currencyCode: "EUR",
    shortDescription: "Imperial museums, coffeehouse culture, and green parks.",
    longDescription:
      "Vienna suits travelers who enjoy museums, classical architecture, and unhurried café stops. Public transport makes the city easy to navigate.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 86,
    searchKeywords: ["vienna", "wien"],
    categories: ["ART_AND_CULTURE", "HISTORY", "FOOD", "ARCHITECTURE"],
    bestFor: ["CULTURAL_TRIPS", "COUPLES", "FAMILIES"],
    practicalNotes:
      "U-Bahn and trams are reliable. Many museums close Mondays. Coffeehouses remain a classic pause between sights.",
  },
  {
    slug: "berlin",
    name: "Berlin",
    type: "CITY",
    countryCode: "DE",
    countryName: "Germany",
    regionName: "Berlin",
    latitude: 52.52,
    longitude: 13.405,
    timezone: "Europe/Berlin",
    primaryLanguage: "de",
    currencyCode: "EUR",
    shortDescription: "Layered history, creative neighborhoods, and a broad food scene.",
    longDescription:
      "Berlin is spread out and neighborhood-driven. Prioritize a few districts rather than trying to cover everything in one pass.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 91,
    searchKeywords: ["berlin", "germany"],
    categories: ["HISTORY", "NIGHTLIFE", "ART_AND_CULTURE", "FOOD"],
    bestFor: ["FRIEND_GROUPS", "SOLO_TRAVELERS", "CULTURAL_TRIPS"],
    practicalNotes:
      "U-Bahn and S-Bahn cover long distances. Some areas feel sparse between landmarks. Cash is still useful in smaller venues.",
  },
  {
    slug: "copenhagen",
    name: "Copenhagen",
    type: "CITY",
    countryCode: "DK",
    countryName: "Denmark",
    regionName: "Capital Region",
    latitude: 55.6761,
    longitude: 12.5683,
    timezone: "Europe/Copenhagen",
    primaryLanguage: "da",
    currencyCode: "DKK",
    shortDescription: "Design-forward neighborhoods, bikes, and waterfront walks.",
    longDescription:
      "Copenhagen is compact enough for walking and cycling. Food and design are often part of the travel rhythm.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 84,
    searchKeywords: ["copenhagen", "københavn"],
    categories: ["FOOD", "ARCHITECTURE", "FAMILY", "RELAXATION"],
    bestFor: ["COUPLES", "FAMILIES", "FOOD_TRIPS"],
    practicalNotes:
      "Bikes and metro are common. Prices can feel high for dining and lodging. Weather changes quickly.",
  },
  {
    slug: "athens",
    name: "Athens",
    type: "CITY",
    countryCode: "GR",
    countryName: "Greece",
    regionName: "Attica",
    latitude: 37.9838,
    longitude: 23.7275,
    timezone: "Europe/Athens",
    primaryLanguage: "el",
    currencyCode: "EUR",
    shortDescription: "Ancient landmarks with a lively modern city around them.",
    longDescription:
      "Athens combines major archaeological sites with neighborhood dining and island ferry connections.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 85,
    searchKeywords: ["athens", "acropolis"],
    categories: ["HISTORY", "FOOD", "ARCHITECTURE", "NIGHTLIFE"],
    bestFor: ["FIRST_TIME_VISITORS", "CULTURAL_TRIPS", "BUDGET_TRAVELERS"],
    practicalNotes:
      "Metro reaches major sites. Summers are hot—plan outdoor ruins for cooler hours. Ferries connect to nearby islands.",
  },
  {
    slug: "cappadocia",
    name: "Cappadocia",
    type: "REGION",
    countryCode: "TR",
    countryName: "Türkiye",
    regionName: "Central Anatolia",
    latitude: 38.6431,
    longitude: 34.8289,
    timezone: "Europe/Istanbul",
    primaryLanguage: "tr",
    currencyCode: "TRY",
    shortDescription: "Fairy chimneys, valley hikes, and cave-side stays.",
    longDescription:
      "Cappadocia is a region of valleys and unique rock formations. Base towns like Göreme make day hikes and viewpoints easy to reach.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 93,
    searchKeywords: ["cappadocia", "goreme", "kapadokya"],
    categories: ["NATURE", "PHOTOGRAPHY", "ADVENTURE", "ROMANTIC"],
    bestFor: ["COUPLES", "FIRST_TIME_VISITORS", "WEEKEND_TRIPS"],
    practicalNotes:
      "Base in a central town for short drives to valleys. Weather can limit outdoor plans. Balloon flights are weather-dependent and optional.",
    isFeatured: true,
    featuredPosition: 6,
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    type: "CITY",
    countryCode: "JP",
    countryName: "Japan",
    regionName: "Kantō",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    primaryLanguage: "ja",
    currencyCode: "JPY",
    shortDescription: "Neighborhoods with distinct character, food culture, and efficient transit.",
    longDescription:
      "Tokyo is best approached neighborhood by neighborhood. Transit makes long distances manageable; food exploration can fill entire days.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 4,
    maximumRecommendedDays: 7,
    popularityScore: 99,
    searchKeywords: ["tokyo", "japan"],
    categories: ["FOOD", "SHOPPING", "NIGHTLIFE", "ART_AND_CULTURE"],
    bestFor: ["FIRST_TIME_VISITORS", "FOOD_TRIPS", "SOLO_TRAVELERS", "LONG_STAYS"],
    practicalNotes:
      "Trains and metro are the backbone of travel. IC cards simplify transit. Cash remains useful at some smaller venues.",
    isFeatured: true,
    featuredPosition: 7,
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    type: "CITY",
    countryCode: "JP",
    countryName: "Japan",
    regionName: "Kansai",
    latitude: 35.0116,
    longitude: 135.7681,
    timezone: "Asia/Tokyo",
    primaryLanguage: "ja",
    currencyCode: "JPY",
    shortDescription: "Temples, gardens, and historic districts with a calmer pace than Tokyo.",
    longDescription:
      "Kyoto suits travelers who want historic sites and quieter neighborhoods. Early starts help at popular temples.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 94,
    searchKeywords: ["kyoto", "japan"],
    categories: ["HISTORY", "NATURE", "PHOTOGRAPHY", "ART_AND_CULTURE"],
    bestFor: ["COUPLES", "CULTURAL_TRIPS", "FIRST_TIME_VISITORS"],
    practicalNotes:
      "Buses and trains cover major areas. Popular sites get crowded midday. Comfortable walking shoes help.",
  },
  {
    slug: "bangkok",
    name: "Bangkok",
    type: "CITY",
    countryCode: "TH",
    countryName: "Thailand",
    regionName: "Bangkok",
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: "Asia/Bangkok",
    primaryLanguage: "th",
    currencyCode: "THB",
    shortDescription: "Temples, markets, and a dense food scene across a sprawling capital.",
    longDescription:
      "Bangkok rewards food-focused travelers and those who mix temples with river and neighborhood time. Traffic can be heavy—transit helps.",
    budgetLevel: "BUDGET",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 92,
    searchKeywords: ["bangkok", "thailand"],
    categories: ["FOOD", "SHOPPING", "NIGHTLIFE", "ART_AND_CULTURE"],
    bestFor: ["FOOD_TRIPS", "BUDGET_TRAVELERS", "FRIEND_GROUPS"],
    practicalNotes:
      "BTS/MRT reduce traffic friction. Heat and humidity are significant. Street food is a highlight for many visitors.",
  },
  {
    slug: "singapore",
    name: "Singapore",
    type: "CITY",
    countryCode: "SG",
    countryName: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    primaryLanguage: "en",
    currencyCode: "SGD",
    shortDescription: "Compact city-state with efficient transit and diverse food.",
    longDescription:
      "Singapore is easy to navigate and well suited to short stays. Neighborhoods and food halls offer variety without long travel times.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 88,
    searchKeywords: ["singapore"],
    categories: ["FOOD", "SHOPPING", "FAMILY", "ARCHITECTURE"],
    bestFor: ["FAMILIES", "FOOD_TRIPS", "WEEKEND_TRIPS"],
    practicalNotes:
      "MRT covers most visitor needs. Strict local rules apply in public spaces. Dining can range widely in price.",
  },
  {
    slug: "bali",
    name: "Bali",
    type: "ISLAND",
    countryCode: "ID",
    countryName: "Indonesia",
    regionName: "Bali",
    latitude: -8.3405,
    longitude: 115.092,
    timezone: "Asia/Makassar",
    primaryLanguage: "id",
    currencyCode: "IDR",
    shortDescription: "Island regions spanning beaches, rice terraces, and temple towns.",
    longDescription:
      "Bali is a destination cluster of distinct areas. Choose a base that matches beach, culture, or nature priorities rather than trying to cover everything.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 5,
    maximumRecommendedDays: 10,
    popularityScore: 94,
    searchKeywords: ["bali", "ubud", "canggu"],
    categories: ["BEACH", "NATURE", "WELLNESS", "RELAXATION"],
    bestFor: ["COUPLES", "REMOTE_WORK", "BEACH_HOLIDAYS", "LONG_STAYS"],
    practicalNotes:
      "Scooters and private transfers are common between areas. Distances look short but traffic varies. Choose a base carefully.",
    isFeatured: true,
    featuredPosition: 8,
  },
  {
    slug: "new-york-city",
    name: "New York City",
    type: "CITY",
    countryCode: "US",
    countryName: "United States",
    regionName: "New York",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    primaryLanguage: "en",
    currencyCode: "USD",
    shortDescription: "Dense neighborhoods, museums, and a fast urban pace.",
    longDescription:
      "New York rewards focused neighborhood days. Transit and walking cover most visitor needs; prioritize rather than overpacking.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 96,
    searchKeywords: ["new york", "nyc", "manhattan"],
    categories: ["ART_AND_CULTURE", "FOOD", "NIGHTLIFE", "SHOPPING"],
    bestFor: ["FIRST_TIME_VISITORS", "FRIEND_GROUPS", "FOOD_TRIPS"],
    practicalNotes:
      "Subway is the practical backbone. Distances between boroughs matter. Weather swings by season.",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    type: "CITY",
    countryCode: "US",
    countryName: "United States",
    regionName: "California",
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: "America/Los_Angeles",
    primaryLanguage: "en",
    currencyCode: "USD",
    shortDescription: "Hills, waterfront views, and distinctive neighborhoods.",
    longDescription:
      "San Francisco is compact but hilly. Neighborhood character changes quickly across short distances.",
    budgetLevel: "PREMIUM",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 83,
    searchKeywords: ["san francisco", "sf"],
    categories: ["FOOD", "NATURE", "ARCHITECTURE", "PHOTOGRAPHY"],
    bestFor: ["COUPLES", "WEEKEND_TRIPS", "FOOD_TRIPS"],
    practicalNotes:
      "Public transit and walking work in central areas. Fog and cool summers surprise some visitors. Hills affect walking plans.",
  },
  {
    slug: "mexico-city",
    name: "Mexico City",
    type: "CITY",
    countryCode: "MX",
    countryName: "Mexico",
    regionName: "Mexico City",
    latitude: 19.4326,
    longitude: -99.1332,
    timezone: "America/Mexico_City",
    primaryLanguage: "es",
    currencyCode: "MXN",
    shortDescription: "Museums, markets, and a rich food culture in a vast capital.",
    longDescription:
      "Mexico City is huge—pick neighborhoods intentionally. Food and museums can fill several days without leaving a few areas.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 90,
    searchKeywords: ["mexico city", "cdmx"],
    categories: ["FOOD", "ART_AND_CULTURE", "HISTORY", "NIGHTLIFE"],
    bestFor: ["FOOD_TRIPS", "CULTURAL_TRIPS", "SOLO_TRAVELERS"],
    practicalNotes:
      "Metro and rideshares help with distance. Altitude and traffic affect pacing. Neighborhood choice matters.",
  },
  {
    slug: "buenos-aires",
    name: "Buenos Aires",
    type: "CITY",
    countryCode: "AR",
    countryName: "Argentina",
    regionName: "Buenos Aires",
    latitude: -34.6037,
    longitude: -58.3816,
    timezone: "America/Argentina/Buenos_Aires",
    primaryLanguage: "es",
    currencyCode: "ARS",
    shortDescription: "Neighborhood cafés, late dinners, and a strong cultural calendar.",
    longDescription:
      "Buenos Aires is neighborhood-driven with a late dining culture. Walkable districts pair well with café time and evening plans.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 82,
    searchKeywords: ["buenos aires", "argentina"],
    categories: ["FOOD", "NIGHTLIFE", "ART_AND_CULTURE", "ARCHITECTURE"],
    bestFor: ["FOOD_TRIPS", "COUPLES", "LONG_STAYS"],
    practicalNotes:
      "Subte and walking cover many visitor areas. Dinner often starts late. Neighborhood bases shape the experience.",
  },
  {
    slug: "marrakech",
    name: "Marrakech",
    type: "CITY",
    countryCode: "MA",
    countryName: "Morocco",
    regionName: "Marrakesh-Safi",
    latitude: 31.6295,
    longitude: -7.9811,
    timezone: "Africa/Casablanca",
    primaryLanguage: "ar",
    currencyCode: "MAD",
    shortDescription: "Medina lanes, markets, and courtyard riads.",
    longDescription:
      "Marrakech centers on the medina experience. Plan slower walking days and leave buffer time for getting oriented.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 86,
    searchKeywords: ["marrakech", "marrakesh"],
    categories: ["HISTORY", "SHOPPING", "FOOD", "PHOTOGRAPHY"],
    bestFor: ["COUPLES", "CULTURAL_TRIPS", "FIRST_TIME_VISITORS"],
    practicalNotes:
      "Medina navigation takes patience. Heat can be intense. Private transfers help for day trips outside the city.",
  },
  {
    slug: "cape-town",
    name: "Cape Town",
    type: "CITY",
    countryCode: "ZA",
    countryName: "South Africa",
    regionName: "Western Cape",
    latitude: -33.9249,
    longitude: 18.4241,
    timezone: "Africa/Johannesburg",
    primaryLanguage: "en",
    currencyCode: "ZAR",
    shortDescription: "Mountain-meets-ocean scenery with wine country day trips.",
    longDescription:
      "Cape Town combines dramatic landscape with neighborhood dining and coastal drives. Weather and wind can shape outdoor plans.",
    budgetLevel: "MODERATE",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 6,
    popularityScore: 85,
    searchKeywords: ["cape town", "south africa"],
    categories: ["NATURE", "FOOD", "ADVENTURE", "PHOTOGRAPHY"],
    bestFor: ["COUPLES", "FRIEND_GROUPS", "FOOD_TRIPS"],
    practicalNotes:
      "A car helps for coastal and wine routes. Wind and weather change quickly on outdoor days. Choose neighborhoods with transport in mind.",
  },
  {
    slug: "santorini",
    name: "Santorini",
    type: "ISLAND",
    countryCode: "GR",
    countryName: "Greece",
    regionName: "South Aegean",
    latitude: 36.3932,
    longitude: 25.4615,
    timezone: "Europe/Athens",
    primaryLanguage: "el",
    currencyCode: "EUR",
    shortDescription: "Cliffside villages, caldera views, and Aegean sunsets.",
    longDescription:
      "Santorini is compact but popular. Plan around viewpoints and quieter villages if crowds are a concern.",
    budgetLevel: "LUXURY",
    minimumRecommendedDays: 2,
    maximumRecommendedDays: 4,
    popularityScore: 91,
    searchKeywords: ["santorini", "thira"],
    categories: ["BEACH", "ROMANTIC", "PHOTOGRAPHY", "RELAXATION"],
    bestFor: ["COUPLES", "BEACH_HOLIDAYS", "LUXURY_TRAVELERS"],
    practicalNotes:
      "Buses and taxis connect villages. Summer crowds and heat are significant. Shoulder seasons can feel easier.",
  },
  {
    slug: "amalfi-coast",
    name: "Amalfi Coast",
    type: "COASTAL_AREA",
    countryCode: "IT",
    countryName: "Italy",
    regionName: "Campania",
    latitude: 40.634,
    longitude: 14.6027,
    timezone: "Europe/Rome",
    primaryLanguage: "it",
    currencyCode: "EUR",
    shortDescription: "Cliff towns, coastal roads, and Mediterranean viewpoints.",
    longDescription:
      "The Amalfi Coast is a string of towns rather than a single city. Pick a base and use buses or ferries between stops.",
    budgetLevel: "LUXURY",
    minimumRecommendedDays: 3,
    maximumRecommendedDays: 5,
    popularityScore: 89,
    searchKeywords: ["amalfi", "positano", "amalfi coast"],
    categories: ["BEACH", "ROMANTIC", "FOOD", "PHOTOGRAPHY"],
    bestFor: ["COUPLES", "LUXURY_TRAVELERS", "FOOD_TRIPS"],
    practicalNotes:
      "Roads are winding and busy in peak season. Ferries can be easier than driving. Book lodging early in summer.",
  },
];

async function seed() {
  if (process.env.NODE_ENV === "production" && process.env.ALLOW_PROD_SEED !== "true") {
    throw new Error(
      "Refusing to seed in production without ALLOW_PROD_SEED=true. Development seed only.",
    );
  }

  const now = new Date();
  let upserted = 0;

  for (const raw of SEED_DESTINATIONS) {
    const item = applyTurkishDestinationContent(raw);
    await prisma.destination.upsert({
      where: { slug: item.slug },
      create: {
        slug: item.slug,
        name: item.name,
        normalizedName: normalizeDestinationName(item.name),
        type: item.type,
        status: "ACTIVE",
        countryCode: item.countryCode,
        countryName: item.countryName,
        regionName: item.regionName,
        latitude: item.latitude,
        longitude: item.longitude,
        timezone: item.timezone,
        primaryLanguage: item.primaryLanguage,
        currencyCode: item.currencyCode,
        shortDescription: item.shortDescription,
        longDescription: item.longDescription,
        budgetLevel: item.budgetLevel,
        minimumRecommendedDays: item.minimumRecommendedDays,
        maximumRecommendedDays: item.maximumRecommendedDays,
        popularityScore: item.popularityScore,
        searchKeywords: item.searchKeywords.map(normalizeDestinationName),
        categories: item.categories,
        bestFor: item.bestFor,
        practicalNotes: item.practicalNotes,
        isFeatured: item.isFeatured ?? false,
        featuredPosition: item.featuredPosition,
        publishedAt: now,
        providerReferences: {
          create: {
            provider: "MANUAL",
            providerDestinationId: `curated:${item.slug}`,
            providerType: item.type,
            rawName: item.name,
            lastSyncedAt: now,
          },
        },
      },
      update: {
        name: item.name,
        normalizedName: normalizeDestinationName(item.name),
        type: item.type,
        status: "ACTIVE",
        countryCode: item.countryCode,
        countryName: item.countryName,
        regionName: item.regionName,
        latitude: item.latitude,
        longitude: item.longitude,
        timezone: item.timezone,
        primaryLanguage: item.primaryLanguage,
        currencyCode: item.currencyCode,
        shortDescription: item.shortDescription,
        longDescription: item.longDescription,
        budgetLevel: item.budgetLevel,
        minimumRecommendedDays: item.minimumRecommendedDays,
        maximumRecommendedDays: item.maximumRecommendedDays,
        popularityScore: item.popularityScore,
        searchKeywords: item.searchKeywords.map(normalizeDestinationName),
        categories: item.categories,
        bestFor: item.bestFor,
        practicalNotes: item.practicalNotes,
        isFeatured: item.isFeatured ?? false,
        featuredPosition: item.featuredPosition,
        publishedAt: now,
        archivedAt: null,
      },
    });
    upserted += 1;
  }

  console.log(`Seeded ${upserted} curated destinations (upsert by slug).`);
}

seed()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
